@startuml

start
:距離センサ用Obj初期化;
:キャタピラ用Obj初期化;
:幅寄せ対象最大距離の設定;
:幅寄せ対象最小距離の設定;
:判定値初期化;

repeat
    :センサから距離を取得;    

    if (取得距離>幅寄せ対象最大距離 && 判定値<=50) then (yes)
    :キャタピラの停止;
        note left
        車は止まっていない
        end note
    :判定値=0;    
    elseif (取得距離>幅寄せ対象最大距離 && 判定値>50) then (yes)
    :キャタピラの後退;
        note left
        車いなくなった
        end note
    :判定値-=1;
    elseif (取得距離<幅寄せ対象最小距離) then (yes)
    :キャタピラの停止;
        note left
        近すぎるから停止
        end note
    elseif (取得距離<幅寄せ対象最大距離 && 取得距離>幅寄せ対象最小距離 && 判定値>50) then (yes)
    :キャタピラの前進;
        note left
        対象距離内に車がいる
        5秒たった
        end note
    :判定値+=1;
    elseif (取得距離<幅寄せ対象最大距離 && 取得距離>幅寄せ対象最小距離 && 判定値<=50) then (yes)
    :判定値+=1;    
        note left
        5秒数える
        end note
    else (該当なし)
    :キャタピラの停止;
    endif

    :0.1秒処理を待つ;
repeat while ()



@enduml
